// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// /// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpU_wgkIuDvgVKay3DOhEXNlFdXW8y5Ds',
    appId: '1:981943043761:web:922a5ce3ce4c6ee1c0c490',
    messagingSenderId: '981943043761',
    projectId: 'th-yr-4802a',
    authDomain: 'th-yr-4802a.firebaseapp.com',
    storageBucket: 'th-yr-4802a.firebasestorage.app',
    measurementId: 'G-9SC0K0PMGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDajC-KyayuJP83RKw93E1ayLmreM5W-9o',
    appId: '1:981943043761:android:0eb66251c125bdfec0c490',
    messagingSenderId: '981943043761',
    projectId: 'th-yr-4802a',
    storageBucket: 'th-yr-4802a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZ7dKjdrTloIxvhA89w55fqAzEkE8WJw',
    appId: '1:981943043761:ios:d9daa630299d9a8dc0c490',
    messagingSenderId: '981943043761',
    projectId: 'th-yr-4802a',
    storageBucket: 'th-yr-4802a.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZ7dKjdrTloIxvhA89w55fqAzEkE8WJw',
    appId: '1:981943043761:ios:d9daa630299d9a8dc0c490',
    messagingSenderId: '981943043761',
    projectId: 'th-yr-4802a',
    storageBucket: 'th-yr-4802a.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpU_wgkIuDvgVKay3DOhEXNlFdXW8y5Ds',
    appId: '1:981943043761:web:9e36c53f609b3133c0c490',
    messagingSenderId: '981943043761',
    projectId: 'th-yr-4802a',
    authDomain: 'th-yr-4802a.firebaseapp.com',
    storageBucket: 'th-yr-4802a.firebasestorage.app',
    measurementId: 'G-G6JMQL9T8Q',
  );
}
